worker_processes 1;
pid logs/nginx-itphlies.pid;

events {
    worker_connections 1024;
}

http {
    default_type application/octet-stream;
    types {
        text/html html htm shtml;
        text/css css;
        text/xml xml;
        application/javascript js mjs;
        application/json json;
        application/wasm wasm;
        image/svg+xml svg svgz;
        image/png png;
        image/jpeg jpg jpeg;
        image/gif gif;
        font/woff woff;
        font/woff2 woff2;
    }
    types_hash_max_size 4096;
    sendfile on;

    access_log logs/nginx-itphlies-access.log;
    error_log logs/nginx-itphlies-error.log warn;
    client_body_temp_path tmp/nginx/client_body;
    proxy_temp_path tmp/nginx/proxy;
    fastcgi_temp_path tmp/nginx/fastcgi;
    uwsgi_temp_path tmp/nginx/uwsgi;
    scgi_temp_path tmp/nginx/scgi;

    server {
        listen 0.0.0.0:8080;
        server_name _;

        root dashboard/build;
        index index.html;

        location / {
            try_files $uri /index.html;
        }

        location /api/ {
            proxy_pass http://127.0.0.1:4000/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto http;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
