test-e2e:
    scripts/test_e2e.sh

test-recovery-soak runs="10":
    scripts/test_e2e.sh --recovery-soak "{{runs}}"

# Requires a MadNIS runtime and a GammaLoop state generated by the pinned GammaLoop revision.
test-e2e-madnis:
    scripts/test_e2e.sh --madnis

process-rust-breit-wigner-sif:
    scripts/build_process_rust_breit_wigner_sif.sh

symbolica-variable-theta:
    scripts/build_symbolica_variable_theta.sh

sync-ubelix host="ubelix" remote_folder="gammaboard":
    ops/ubelix/sync_ops.sh "{{host}}" "{{remote_folder}}"

# One runner for planning, measuring, summarizing, plotting, and comparing experiments.
benchmark *args:
    python3 scripts/benchmark.py {{args}}
