test-e2e:
    scripts/test_e2e.sh

# Requires a MadNIS runtime and a GammaLoop state generated by the pinned GammaLoop revision.
test-e2e-madnis:
    scripts/test_e2e.sh --madnis

process-rust-breit-wigner-sif:
    scripts/build_process_rust_breit_wigner_sif.sh

symbolica-variable-theta:
    scripts/build_symbolica_variable_theta.sh

benchmark-campaign *args:
    scripts/benchmark_campaign.sh {{args}}
