# Example GammaLoop run.
# Assumes `gammaloop` is a sister folder of `gammaboard`.

name = "gammaloop-triangle"

[evaluator]
kind = "gammaloop"
state_folder = "../gammaloop/my_triangle/state"
momentum_space = true
use_f128 = false
training_projection = "abs"
[evaluator_runner_params]
performance_snapshot_interval_ms = 1000

[sampler_aggregator_runner_params]
frontend_sync_interval_ms = 2000
