name = "live-test"

[evaluator]
kind = "unit"
continuous_dims = 1
discrete_dims = 0

[sampler_aggregator]
kind = "naive_monte_carlo"

[evaluator_runner_params]
performance_snapshot_interval_ms = 2000
min_tick_time_ms = 50
