name = "python-scalar-python-sampler-flake-demo"

[evaluator]
kind = "python_scalar"
flake_ref = "path:./python_api/examples/python_scalar_sin#runtime"
module = "demo_integrand"
class = "SinIntegrand"
continuous_dims = 1
discrete_dims = 0
init_args = { scale = 1.0, bias = 0.0 }

[[task_queue]]
name = "sample-a"
kind = "sample"
nr_samples = 1000
observable = { config = "scalar" }
sampler_aggregator = { config = { kind = "python_homogeneous_monte_carlo", flake_ref = "path:./python_api/examples/python_sampler_monte_carlo#runtime", module = "demo_sampler", class = "BasicMonteCarloSampler", continuous_dims = 1, discrete_dims = 0, init_args = { seed = 0, training_target_samples = 0 } } }
