name = "symbolica-poly-test"
target = { kind = "scalar", value = 1.0 }

[evaluator]
kind = "symbolica"
expr = "x^2 + y^2 + z^2"
args = ["x", "y", "z"]

[sampler_aggregator]
kind = "naive_monte_carlo"

[evaluator_runner_params]
performance_snapshot_interval_ms = 2000
