name = "symbolica-sin-test"
target = { kind = "scalar", value = 0.45969769413186023 }

[evaluator]
kind = "symbolica"
expr = "sin(x)"
args = ["x"]

[sampler_aggregator]
kind = "naive_monte_carlo"

[evaluator_runner_params]
performance_snapshot_interval_ms = 2000
min_tick_time_ms = 50
