# Example GammaLoop run.
# Assumes `gammaloop` is a sister folder of `gammaboard`.

name = "tth"

[evaluator]
kind = "gammaloop"
state_folder = "../gammaloop/examples/cli/epem_a_ttxh/LO/state"
integrand_name = "LO"
momentum_space = false


[evaluator_runner_params]
performance_snapshot_interval_ms = 1000

[sampler_aggregator_runner_params]
frontend_sync_interval_ms = 2000

[[task_queue]]
name = "havana-train-10m"
kind = "sample"
nr_samples = 50_000_000
observable = { config = "gammaloop" }
sampler_aggregator = { config = { kind = "havana_training", seed = 0, bins = 128, samples_for_update = 5_000_000, initial_training_rate = 0.05, final_training_rate = 0.005 } }

[[task_queue]]
name = "havana-infer-100m"
kind = "sample"
nr_samples = 100_000_000
sampler_aggregator = { config = { kind = "havana_inference", source = "latest_training_sampler_aggregator" } }
