bin := "./target/dev-optim/gammaboard"
release_bin := "./target/release/gammaboard"
deploy_cfg := "ops/local/config/deploy.toml"
runtime_cfg := "configs/runtime/default.toml"

deploy mode="dev":
    #!/usr/bin/env bash
    set -euo pipefail

    cd ../..
    just build-frontend
    if [[ "{{mode}}" == "release" ]]; then
        just build-backend-release
        deploy_bin="{{release_bin}}"
    else
        just build-backend
        deploy_bin="{{bin}}"
    fi

    exec "${deploy_bin}" --runtime-config "{{runtime_cfg}}" deploy run --deploy-config "{{deploy_cfg}}"
