host = "127.0.0.1"
port = 4000
allowed_origins = [
    "http://localhost:8080",
    "http://itphlies:8080",
]
secure_cookie = false
allow_db_admin = true
run_templates_dir = "../runs"
task_templates_dir = "../tasks"

[auth]
admin_password_hash = "$argon2id$v=19$m=19456,t=2,p=1$IlJKLA7MFGA5iaXoS0KnGQ$ukiPLlZKlWme0artScJVv7dfc/mslAB2Cy9MbM1mDjk"
session_secret = "VU8l2fh4VKEhWLtxAT4s"
