# Short Havana train/infer sequence.

[[task_queue]]
name = "train"
kind = "sample"
stop_condition = { max_samples = 1_000 }
accumulator = { config = "complex" }
sampler_aggregator = { config = { kind = "havana_training" } }

[[task_queue]]
name = "infer"
kind = "sample"
stop_condition = { max_samples = 1_000 }
sampler_aggregator = { config = { kind = "havana_inference" } }
