bin := "../../target/dev-optim/gammaboard"
release_bin := "../../target/release/gammaboard"
deploy_cfg := "config/deploy.toml"

deploy mode="release":
    #!/usr/bin/env bash
    set -euo pipefail

    just --justfile ../../justfile build-frontend
    if [[ "{{mode}}" == "release" ]]; then
        just --justfile ../../justfile build-backend-release
        {{release_bin}} deploy up --deploy-config "{{deploy_cfg}}" --mode "{{mode}}"
    else
        just --justfile ../../justfile build-backend
        {{bin}} deploy up --deploy-config "{{deploy_cfg}}" --mode "{{mode}}"
    fi

status:
    {{bin}} deploy status --deploy-config "{{deploy_cfg}}"

down:
    {{bin}} deploy down --deploy-config "{{deploy_cfg}}"
