# Update stage state without producing work.
# Omit fields you want to inherit from the previous stage.

[[task_queue]]
kind = "configure"
observable = "scalar"

[task_queue.sampler_aggregator]
kind = "naive_monte_carlo"

[task_queue.parametrization]
kind = "identity"
