# Complex Havana inference sampling.
# This expects a previous stage snapshot with persisted Havana state.

[[task_queue]]
kind = "sample"
nr_samples = 1_000_000
observable = "complex"

[task_queue.sampler_aggregator]
kind = "havana_inference"

[task_queue.parametrization]
kind = "havana_inference"

[task_queue.parametrization.inner]
kind = "identity"
