# Complex Havana inference sampling.

[[task_queue]]
kind = "sample"
nr_samples = 1000
observable = "complex"

[task_queue.sampler_aggregator]
kind = "havana_training"

[[task_queue]]
kind = "sample"
nr_samples = 1000
observable = "complex"

[task_queue.sampler_aggregator]
kind = "havana_inference"

[task_queue.materializer]
kind = "havana_inference"
