# todo: create run-cargd to make the state

name = "gammaloop-triangle"
[[task_queue]]
kind = "image"
[task_queue.geometry]
offset = [0.0, 0.0, 0.0]
u_vector = [1.0, 0.0, 0.0]
v_vector = [0.0, 0.0, 1.0]
u_linspace = { start = -2.0, stop = 2.0, count = 128 }
v_linspace = { start = -2.0, stop = 2.0, count = 128 }
discrete = []

[[task_queue]]
kind = "sample"
nr_samples = 500_000
[task_queue.sampler_aggregator]
kind = "havana_training"
seed = 0
bins = 64
min_samples_for_update = 1024
samples_for_update = 16384
initial_training_rate = 0.1
final_training_rate = 0.001
[task_queue.parametrization]
kind = "identity"

[[task_queue]]
kind = "sample"
nr_samples = 1_000_000
[task_queue.sampler_aggregator]
kind = "havana_inference"
[task_queue.parametrization]
kind = "havana_inference"
[task_queue.parametrization.inner]
kind = "identity"

[[task_queue]]
kind = "pause"

[evaluator]
kind = "gammaloop"
# Path to a pre-generated GammaLoop state folder containing model/process/integrand artifacts.
state_folder = "/home/cedricsigrist/Workspace/repos/gammaloop/my_triangle/state"
# process_id = 0
# integrand_name = "triangle"
momentum_space = false
use_f128 = false
training_projection = "abs"
observable_kind = "complex"
continuous_dims = 3
discrete_dims = 0

[parametrization]
kind = "identity" # "spherical"

[evaluator_runner_params]
min_loop_time_ms = 5
performance_snapshot_interval_ms = 2000

[sampler_aggregator_runner_params]
min_poll_time_ms = 50
performance_snapshot_interval_ms = 2000
target_batch_eval_ms = 200.0
target_queue_remaining = 0.8
max_batch_size = 10_000
max_batches_per_tick = 128
max_queue_size = 128
completed_batch_fetch_limit = 128
