host = "0.0.0.0"
port = 4000
allowed_origin = "http://localhost:3000"
secure_cookie = false

[auth]
admin_password_hash = "$argon2id$v=19$m=19456,t=2,p=1$IlJKLA7MFGA5iaXoS0KnGQ$ukiPLlZKlWme0artScJVv7dfc/mslAB2Cy9MbM1mDjk"
session_secret = "VU8l2fh4VKEhWLtxAT4s"
