name = "symbolica-sin-test"
target = { kind = "scalar", value = 0.45969769413186023 }

[evaluator]
kind = "symbolica"
expr = "sin(x)"
args = ["x"]

[sampler_aggregator]
kind = "naive_monte_carlo"

[parametrization]
kind = "identity"

[evaluator_runner_params]
min_loop_time_ms = 0
performance_snapshot_interval_ms = 2000

[sampler_aggregator_runner_params]
min_poll_time_ms = 100
performance_snapshot_interval_ms = 2000
target_batch_eval_ms = 400.0
target_queue_remaining = 0.5
max_batch_size = 64
max_batches_per_tick = 16
max_queue_size = 128
completed_batch_fetch_limit = 1024
