name = "epem_a_tth"
target = { kind = "complex", real = 1.563e-3, imag = 0.0 }

[evaluator]
kind = "gammaloop"
state_folder = "epem_a_ttxh/LO/state"
integrand_name = "LO"


[[task_queue]]
name = "set-accumulator"
kind = "set_accumulator"
accumulator = "gammaloop"
